-- function is included in DB SYS lecture slides
-- to help deal with error messages generated by custom constraints


create or replace 
FUNCTION strip_constraint_name( errmsg VARCHAR2 ) RETURN VARCHAR2 AS
  rp_pos NUMBER;
  dot_pos NUMBER;
BEGIN
  dot_pos := INSTR(errmsg, '.');
  rp_pos := INSTR(errmsg, ')');
  IF (dot_pos = 0 OR rp_pos = 0 ) THEN
    RETURN(NULL);
    ELSE
  RETURN(UPPER(SUBSTR(errmsg, dot_pos+1, rp_pos-dot_pos-1)));
  END IF;
END;
/


-- the same function with a different name has been observed in some lecture slide examples etc, s
-- consequently the same function is included under the two different names in case students use alternate 
-- naming convention.
 
create or replace 
FUNCTION strip_constraint( errmsg VARCHAR2 ) RETURN VARCHAR2 AS
  rp_pos NUMBER;
  dot_pos NUMBER;
BEGIN
  dot_pos := INSTR(errmsg, '.');
  rp_pos := INSTR(errmsg, ')');
  IF (dot_pos = 0 OR rp_pos = 0 ) THEN
    RETURN(NULL);
    ELSE
  RETURN(UPPER(SUBSTR(errmsg, dot_pos+1, rp_pos-dot_pos-1)));
  END IF;
END;